#propiedad, valor de la propiedad
spring.datasource.url=jdbc:postgresql://localhost:5432/scheduler
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
