spring.application.name=agenda-terapeutas
spring.profiles.active=dev

#OAuth2
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com

#rendering
spring.jpa.open-in-view=true
